
# Tarea S9.01. Creación de funciones, estructuras de datos y bucles

## Nivel 1

### **1. Calculadora del índice de masa corporal**

Escribe una función que calcule el IMC ingresado por el usuario/a, es decir, quien lo ejecute deberá ingresar estos datos. Puedes obtener más información de su cálculo en: 🔗 Índice de masa corporal IMC que es y cómo se calcula.

La función debe clasificar el resultado en sus respectivas categorías.

Consejo: Intenta validar los datos previamente, para que envíe un mensaje de advertencia si los datos introducidos por el usuario/a no están en el formato adecuado o no toma valores razonables.

In [1]:
def measure_request(prompt, max_value):
    while True:
        try:
            # input and safegard for floats and values with commas
            value = float(input(prompt).replace(",","."))
            # limit value input using raise ValueError
            if value <= 0 or value > max_value:
                raise ValueError
        except ValueError:
            print("Make sure to enter a number and a reasonable measure")
        else:
            return value
        
def imc_categorization(weight, height):
    imc = weight / (height ** 2)
    if imc < 18.5:
        print("Your result: Underweight")
    elif imc < 25:
        print("Your result: Normal weight")
    elif imc < 30:
        print("Your result: Overweight")
    else: 
        print("Your result: Obesity")

user_weight = measure_request("Insert your weight in kg", 600)
user_height = measure_request("Insert your height in meters", 3)

imc_categorization(user_weight, user_height)

Your result: Overweight

### Note: 
Using a single function to request measures (height and weight) and to add safeguards such as making sure the value that is returned is float and is a reasonable measurement (using limits to avoid negative numbers or numbers that are too high based on each measure)

### **2. Conversor de temperaturas**

Existen diversas unidades de temperatura utilizadas en distintos contextos y regiones. Las más comunes son Celsius (°C), Fahrenheit (°F) y Kelvin (K). También existen otras unidades como Rankine (°Ra) y Réaumur (°Re).

Selecciona al menos 2 conversores, de modo que al introducir una temperatura devuelva, como mínimo, dos conversiones, de modo que se puedan guardar (recuerda que un print() no se puede guardar nunca).

Consejo: Intenta validar los datos previamente, para que envíe un mensaje de advertencia si los datos introducidos por el usuario/a no están en el formato adecuado.

(EXTRA): Piensa una manera de almacenar todas las posibles conversiones en un solo objeto (¿Lista? ¿Diccionario? ¿DataFrame?) en vez de escribir muchos if else en función de la temperatura de origen y la temperatura de destino.

In [2]:
import pandas as pd

# defining temp values that are accepted 
valid_temps = ["celsius", "fahrenheit", "kelvin"]

# Creating a dataframe to store all conversion formulas as string
df = {
    "celsius": ["x", "(x - 32) * (5/9)", "x - 273.15"],
    "fahrenheit": ["x * 1.8 + 32", "x", "(x - 273.15) * 1.8 + 32"],
    "kelvin": ["x + 273.15", "(x - 32) * (5/9) + 273.15", "x"]
}

df = pd.DataFrame(df, index = ["celsius", "fahrenheit", "kelvin"])

def temp_request():
    while True:
        try:
            temp_start = input('Insert start temperature').lower()
            if temp_start not in valid_temps:
                raise ValueError  # added safeguard to only accept the valid temperatures using raise ValueError
            value = float(input('Insert value').replace(",","."))
        except ValueError:
            print(f"Make sure to enter a valid temperature {valid_temps} and a number as value")
        else:
            return temp_start, value
        
def temp_converter(temp_start, value, df = df):
    x = value # defining the value that the function receives as x which will be used for the calculations in the temp formulas
    results = {}
    for temp_final in valid_temps:
        formula = df.loc[temp_start, temp_final] 
        results[temp_final] = round(eval(formula), 2) # using eval to do the calculations in the strings
    return results


print(temp_converter(*temp_request()))

{'celsius': 25.0, 'fahrenheit': 77.0, 'kelvin': 298.15}

### Note
Using dataframes to keep the information of the formulas in strings and then evaluating the expressions with eval to get the results of each conversion.
Getting input from user of the temperature and value to use to convert to the other two valid temperatures. The input has a safeguard to ensure the values added by the user are found in the dataframe and replacing , to . in case someone uses ,

### **3. Contador de palabras de un texto.**

Escribe una función que dado un texto, muestre las veces que aparece cada palabra. Intenta que se gestionen todas las posibles casuísticas que hagan que el programa no funcione correctamente.

(EXTRA): ¿Cuál es la longitud media de las palabras del texto que has escrito? “¿Hola cómo va?” debería devolver (4+3+2) / 3 = 3

In [3]:
import string # importing string module to use constant for punctuation

def text_splitting():
    while True:
        text = input("Input a text")
        if text == "" or text == " ": # adding safeguard to avoid empty inputs
            print("Make sure to enter a text")
        else:
            punctuation = "¡¿" + string.punctuation # adding more symbols to the punctuation string gotten from the string.punctuation constant
            clean_text = text.lower().strip(punctuation) 
            return clean_text.split() 

def count_words(word_list):
        phrase_dictionary = {}
        for word in word_list:
            word_summatory = word_list.count(word) # getting the count of each word in the word_list
            phrase_dictionary[word] = word_summatory
        return phrase_dictionary

def word_average(word_list):
    return round(len(("".join(word_list)))/len(word_list), 2) # using join to change list to string without spaces

word_list = text_splitting()

print("Word count:", count_words(word_list)) 
print("Word average:", word_average(word_list))

Word count: {'hola': 1, 'cómo': 1, 'va': 1}
Word average: 3.33

### **4. Diccionario inverso (con posibilidad de duplicados)**

Resulta que el cliente tiene una encuesta muy antigua que se almacena en un diccionario y los resultados los necesita a la inversa, es decir, intercambiando las claves y valores. Los valores y claves en el diccionario original son únicos; si éste no es el caso, la función debería imprimir un mensaje de advertencia, junto con una lista con los valores asociados a la clave repetida.

In [4]:
def reverse_dictionary(dictionary):
    final_dictionary = {}
    duplicated_values = []
    
    for key, value in dictionary.items():
        if value not in final_dictionary: 
            final_dictionary[value] = key # adding items when they are not in the final_dictionary yet
        else:
            duplicated_values.append(value) # adding duplicated values which where already in the final_dictionary in list
            if isinstance(final_dictionary[value], list): # determining if a value in the dictionary is a list, which means a key with duplications was already created
                final_dictionary[value].append(key) # appending the new value to the list within the dictionary
            else:
                final_dictionary[value] = [final_dictionary[value], key] # first duplicate which creates the list, keeps the old value and adds the new one

    if len(duplicated_values) > 0: # checks if there are any duplicates in the duplicated_values list to print a warning
        for value in duplicated_values:
            print("Warning: The following key is duplicated ", value, final_dictionary.get(value)) # using set to show unique values
    
    return final_dictionary

start_dictionary = {"a": 1, "b": 2, "c":3, "d": 4, "e": 4, "f": 5}

print(reverse_dictionary(start_dictionary))

Warning: The following key is duplicated  4 ['d', 'e']
{1: 'a', 2: 'b', 3: 'c', 4: ['d', 'e'], 5: 'f'}

## Nivel 2

### **1. Contador y ordenador de palabras de un texto.**

El cliente quedó contento con el contador de palabras, pero ahora quiere leer archivos TXT y que calcule la frecuencia de cada palabra ordenadas dentro de las entradas habituales del diccionario según la letra con la que comienzan, es decir, las claves deben ir de la A a la Z y dentro de la A debemos ir de la A a Z. "tu_me_quieres_blanca.txt" la salida esperada sería:

In [5]:
import pandas as pd
import string

poem_df = pd.read_csv("/Users/valeriaontaneda/Documents/It_Academy/Especializacion/Sprint 9/tu me quieres blanca.txt", sep="\t") # using pandas to upload data using tab as separator

def clean_poem_list(dataframe):
    punctuation = "¡¿" + string.punctuation
    poem = dataframe.to_string(index=False)
    translation_table = str.maketrans("","",punctuation) # creating trans table and passing punctuation as third argument to remove all punctuations
    poem_clean = poem.lower().translate(translation_table) # using the trans table created to apply it to the poem
    poem_list = poem_clean.split() 
    poem_list.sort() 
    return poem_list 

def word_count_dictionary(list):
    word_dictionary = {}
    for word in list:
        word_count = list.count(word) # calculating word count in list
        word_dictionary[word] = word_count
    return word_dictionary 

def nested_word_count_dictionary(dictionary):
    nested_dictionary = {}
    for key, value in dictionary.items():
        letter = key[0] 
        if letter not in nested_dictionary: 
            nested_dictionary[letter] = {} # if the letter is not in the dict, creating key with empty value of the letter
            nested_dictionary[letter][key] = value # adding key-value pair within the letter
        else:
            nested_dictionary[letter][key] = value  
    return nested_dictionary

poem_list = clean_poem_list(poem_df)

print(nested_word_count_dictionary(word_count_dictionary(poem_list)))

{'a': {'a': 3, 'agua': 1, 'al': 2, 'alba': 4, 'alcobas': 1, 'alimenta': 1, 'alma': 1, 'amarga': 1, 'azucena': 1}, 'b': {'baco': 1, 'banquete': 1, 'bebe': 1, 'blanca': 3, 'boca': 1, 'bosques': 1, 'buen': 1}, 'c': {'cabañas': 1, 'carnes': 2, 'casta': 3, 'cerrada': 1, 'con': 4, 'conservas': 1, 'copas': 1, 'corola': 1, 'corriste': 1, 'cuando': 2, 'cubierto': 1, 'cuerpo': 1, 'cuáles': 1}, 'd': {'de': 8, 'dejaste': 1, 'del': 1, 'diga': 1, 'dios': 2, 'duerme': 1}, 'e': {'el': 4, 'ellas': 1, 'en': 4, 'engaño': 1, 'enredada': 1, 'entonces': 1, 'escarcha': 1, 'espumas': 1, 'esqueleto': 1, 'estrago': 1}, 'f': {'festejando': 1, 'filtrado': 1, 'frutos': 1}, 'h': {'habla': 1, 'hacia': 1, 'haya': 1, 'hayas': 1, 'hermana': 1, 'hombre': 1, 'hubiste': 1, 'huye': 1}, 'i': {'intacto': 1}, 'j': {'jardines': 1}, 'l': {'la': 3, 'labios': 1, 'las': 7, 'lo': 2, 'los': 4, 'luna': 1, 'lévate': 1, 'límpiate': 1}, 'm': {'mano': 1, 'manos': 1, 'margarita': 1, 'me': 10, 'mi': 1, 'mieles': 1, 'milagros': 1, 'mojada': 1, 'montaña': 1, 'morados': 1}, 'n': {'negros': 1, 'ni': 2, 'no': 1, 'nácar': 1, 'nívea': 2}, 'p': {'perdone': 2, 'perfume': 1, 'por': 2, 'pretendes': 3, 'preténdeme': 3, 'puesto': 1, 'pájaros': 1, 'pámpanos': 1}, 'q': {'que': 6, 'quedó': 1, 'quieres': 6}, 'r': {'rayo': 1, 'raíz': 1, 'renueva': 1, 'rocas': 1, 'rojo': 1}, 's': {'salitre': 1, 'se': 2, 'sea': 1, 'sean': 1, 'sobre': 2, 'sé': 1}, 't': {'te': 3, 'tejidos': 1, 'tenue': 1, 'tierra': 1, 'toca': 1, 'todas': 2, 'todavía': 1, 'tornadas': 1, 'tú': 8}, 'u': {'un': 1, 'una': 1}, 'v': {'vestido': 1, 'vete': 1, 'vive': 1}, 'y': {'y': 5}}

### **2. Conversión de tipos de datos.**

El cliente recibe una lista de datos y necesita generar dos listas, la primera donde estarán todos los elementos que pudieron convertirse en flotantes y la otra donde están los elementos que no pudieron convertirse.

In [6]:
starter_list = [ '1.3', 'one' , '1e10' , 'seven', '3-1/2', ('2',1,1.4,'not-a-number'), [1,2,'3','3.4']]

def list_flatenning(input_list):
    flatten_list = []
    for item in input_list:
        if isinstance(item, (tuple, list, set)): # using isinstance to determine specific data types
            for subitem in item: # loop of subitem within original list
                flatten_list.append(subitem)
        else:
            flatten_list.append(item)
    return flatten_list

def float_convertor(input_list):
    float_list = []
    string_list = []
    for item in input_list:
        try:
            float_list.append(float(item))
        except ValueError:
            string_list.append(item)
    return float_list, string_list

float_list, string_list = float_convertor(list_flatenning(starter_list)) # calling functions in a way that it unpacks values returned

print("float_list:", float_list)
print("string_list:", string_list)

float_list: [1.3, 10000000000.0, 2.0, 1.0, 1.4, 1.0, 2.0, 3.0, 3.4]
string_list: ['one', 'seven', '3-1/2', 'not-a-number']

## Nivel 3

### **1. Generador de Contraseñas**

Explora el funcionamiento del módulo random de la librería numpy. 🔗 Random module in NumPy

En este punto, el cliente ha detectado un problema con las contraseñas que utilizan sus trabajadores. Asdf1234, fechas de cumpleaños o similares. Para solucionarlo, nos ha encargado una función de Python que genere contraseñas más seguras. La función debe depender de los siguientes parámetros:

- longitud (int): Longitud de la contraseña
- mayúsculas (bool = True): Si tiene que aparecer mayúsculas
- minúsculas (bool = True): Si tiene que aparecer minúsculas
- números (bool = True): Si tiene que aparecer números
- signos (bool = False): Si tiene que aparecer caracteres especiales (,-$? o similares)

Así pues, si ejecutamos la función de la siguiente forma:

crear_contraseña(10, True, True, True, True)

Deberíamos obtener un output (que debemos poder guardar) del estilo:

9Er,5Vn8P$

Asegúrate de que se cumplan todos los criterios, y que estas contraseñas sean realmente aleatorias.

(EXTRA) Explora cómo podríamos hacer que la función copiara la contraseña automáticamente en el portapapeles del ordenador (como si la hubiéramos seleccionado y hecho ctrl+copy).

In [7]:
import numpy as np
import string # using string to get collection of different characters that will be used for the password generation
import pyperclip # importing pyperclip module to copy password in clipboard


def generate_pass(length, lower = True, upper = True, number = True, punctuation = True):
    
    if length >= 8: # validation of minimum length of 8 characters

        password = []
        total_list = []

        # using np.random.permutation to shuffle characters and string to get lowercase, uppercase, digits and punctuation collections
        np_lower_case = np.random.permutation(list(string.ascii_lowercase))
        np_upper_case = np.random.permutation(list(string.ascii_uppercase))
        np_number = np.random.permutation(list(string.digits))
        np_symbol = np.random.permutation(list(string.punctuation))
        
        if lower:
            password.append(str(np_lower_case[0]))
            total_list += list(string.ascii_lowercase)
        if upper:
            password.append(str(np_upper_case[0]))
            total_list += list(string.ascii_uppercase)
        if number:
            password.append(str(np_number[0]))
            total_list += list(string.digits)
        if punctuation:
            password.append(str(np_symbol[0]))
            total_list += list(string.punctuation)

        if len(password) > 1: # adding safeguard to ensure user picks at least 2 character types. Checking len password as the base has the first characters added
            filler_len = length - len(password) # based on the len argument passed in the function, calculate how many characters are missing to match the length
            np_filler = np.random.choice(total_list, size=filler_len) # using random.choice to add missing characters in a randomize way

            np_password = np.concatenate((np.array(password), np_filler)) # using concatenate to merge the base password with the filler one
            np.random.shuffle(np_password) # using shuffle to randomize the final array and make sure there are no patterns

            string_password = "".join(np_password) # using join to change array to string

            pyperclip.copy(string_password) # using pyperclip to copy pass to the clipboard
            print("The password has been successfully copied to your clipboard")
            
            return string_password
        
        else:
            print("You must select at least two type of characters")
    else:
        print("Your password must be at least 8 characters long")

generate_pass(8, True, True, True, True)

The password has been successfully copied to your clipboard

'1!y;A.=G'

### Note
- Using numpy, string and pyperclip for this password generation.
- There are two safeguards: a min of 8 characters in the password and checking that at least 2 character types have been requested
- Using string to get collections for each character type and permutation from numpy to shuffle the first arrays as the idea is to get the first value [0] to add to the password to make sure at least one character of the types requested is in the password.
- Checking type of characters required, adding the first character of each to the password and creating a list with a mix of type of characters which then will serve to fill the rest of the password.
- Calculating how many characters are left to fill based on the length passed by user and the characters already added to the password
- Using np.choice to get characters from the list with all characters so that it is randomize
- Concatenating both arrays and shuffling again before changing it to a string using join() 
- Finally using pyperclip to copy password to the clipboard

### **2. Procesamiento de datos simple**

Una compañera de trabajo nos ha pedido un favor, aprovechando que sabe que estamos aprendiendo a programar. Tiene un histórico de partidos de fútbol catalán en un fichero, donde se almacenan los nombres de los equipos y los resultados. Necesita que procesemos los datos de forma automática, para extraer los resultados que necesita.

Utiliza el archivo "historic_partits.txt"

Necesita un programa que devuelva:

- El número total de goles que ha marcado cada equipo.
- El nombre del equipo más goleador
- El nombre del equipo más goleado
- La clasificación global (cada victoria: 3 pts, empate 1 pts, derrota 0 pts)

In [2]:
import pandas as pd

# importing data with pandas using tab separator and column names
matches_df = pd.read_csv("/Users/valeriaontaneda/Documents/It_Academy/Especializacion/Sprint 9/historic partits.txt", sep = "\t|-", names = ["home_team", "score_home_team", "score_away_team", "away_team"], engine='python')
matches_df.info() # checking info imported with info and head
matches_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   home_team        500 non-null    str
 1   score_home_team  500 non-null    int64
 2   score_away_team  500 non-null    int64
 3   away_team        500 non-null    str
dtypes: int64(2), str(2)
memory usage: 15.8 KB

    home_team  score_home_team  score_away_team   away_team
0     Manlleu                0                1  Granollers
1  Vilafranca                4                5    Terrassa
2        Olot                5                0  Granollers
3  Vilafranca                5                5     Manlleu
4    Cornellà                5                1        Prat

Using a function to add four new columns to understand the results and scores of the home and away teams 
Using apply to use function in the dataframe created and with axis = 1 to go row by row.
The lambda function receives data of each row as series and from each series passes the arguments needed for the function to return the tuple with the results that is then expanded and creates the 4 new columns with info from each row.

In [3]:
def points_calculation(score_home_team, score_away_team):
    if score_home_team > score_away_team:
        return "win", 3, "lost", 0
    elif score_home_team < score_away_team:
        return "lost", 0, "win", 3
    else:
        return "tie", 1, "tie", 1

# adding 4 new columns and passing the score columns as arguments using apply
matches_df[['result_home_team', 'points_home_team', 'result_away_team', 'points_away_team']] = matches_df[['score_home_team', 'score_away_team']].apply(
    lambda row: points_calculation(row['score_home_team'], row['score_away_team']), axis=1, result_type='expand'
) #using axis=1 to go row by row instead of column by column and expand to separate the tuple in different columns

matches_df.head(10)

,home_team,score_home_team,score_away_team,away_team,result_home_team,points_home_team,result_away_team,points_away_team
0,Manlleu,0,1,Granollers,lost,0,win,3
1,Vilafranca,4,5,Terrassa,lost,0,win,3
2,Olot,5,0,Granollers,win,3,lost,0
3,Vilafranca,5,5,Manlleu,tie,1,tie,1
4,Cornellà,5,1,Prat,win,3,lost,0
5,Cerdanyola,0,5,Vilafranca,lost,0,win,3
6,Sant Andreu,2,3,Cornellà,lost,0,win,3
7,Vilafranca,5,4,Olot,win,3,lost,0
8,FC Barcelona,4,4,Badalona,tie,1,tie,1
9,Granollers,1,5,Sabadell,lost,0,win,3

In [4]:
home_matches_df = matches_df[["home_team","score_home_team", "score_away_team", "result_home_team", "points_home_team"]]
home_matches_df.rename(columns={"home_team" : "teams", "score_home_team" : "goals", "score_away_team" : "goals_received", "result_home_team" : "result", "points_home_team" : "points"}, inplace=True)

away_matches_df = matches_df[["away_team","score_away_team", "score_home_team", "result_away_team", "points_away_team"]]
away_matches_df.rename(columns={"away_team" : "teams", "score_away_team" : "goals", "score_home_team" : "goals_received", "result_away_team" : "result", "points_away_team" : "points"}, inplace=True)

final_matches_df = pd.concat([home_matches_df, away_matches_df], ignore_index=True) # using concat to unify home and away teams with its information
final_matches_df.head()

        teams  goals  goals_received result  points
0     Manlleu      0               1   lost       0
1  Vilafranca      4               5   lost       0
2        Olot      5               0    win       3
3  Vilafranca      5               5    tie       1
4    Cornellà      5               1    win       3

In [5]:
final_matches_df['win'] = (final_matches_df['result'] == 'win').astype(int) # creating columns where win is true and changes to numeric value with astype(int)
final_matches_df['tie'] = (final_matches_df['result'] == 'tie').astype(int)
final_matches_df['lost'] = (final_matches_df['result'] == 'lost').astype(int)

score_board_df = final_matches_df.groupby("teams")[['win', 'tie', 'lost', 'goals', 'goals_received', 'points']].sum().sort_values("points", ascending=False)

score_board_df.head(20)

                     win  tie  lost  goals  goals_received  points
teams
Girona FC             31    3    13    139              94      96
Llagostera            29    7    20    159             142      94
Sabadell              26    7    15    141             121      85
Cornellà              25    7    22    147             146      82
RCD Espanyol          23   11    21    131             144      80
Figueres              23   10    23    161             154      79
Lleida Esportiu       23    6    23    129             133      75
Terrassa              20   14    23    147             164      74
FC Barcelona          22    7    15    125             115      73
Vilafranca            20   12    25    157             172      72
Badalona              18   14    16    134             124      68
Reus Deportiu         20    8    16    119             111      68
Nàstic de Tarragona   20    8    27    130             148      68
Granollers            21    4    24    122             117      67
Olot                  18   10    26    132             144      64
Sant Andreu           17   11    25    123             134      62
Manlleu               16    9    18    106             118      57
Cerdanyola            17    5    28    117             133      56
Prat                  16    8    21    106             111      56
Europa                12    5    16     93              93      41

In [6]:
team_goals = score_board_df[["goals"]].sort_values("goals", ascending=False)
team_goals.head(20)

                     goals
teams
Figueres               161
Llagostera             159
Vilafranca             157
Cornellà               147
Terrassa               147
Sabadell               141
Girona FC              139
Badalona               134
Olot                   132
RCD Espanyol           131
Nàstic de Tarragona    130
Lleida Esportiu        129
FC Barcelona           125
Sant Andreu            123
Granollers             122
Reus Deportiu          119
Cerdanyola             117
Manlleu                106
Prat                   106
Europa                  93

In [7]:
print(team_goals[team_goals.goals == team_goals.goals.max()]) # filter df to show the teams that match the max goals which works to show ties

          goals
teams
Figueres    161

In [8]:
team_goals_received = score_board_df[["goals_received"]].sort_values("goals_received", ascending=False)
print(team_goals_received[team_goals_received.goals_received == team_goals_received.goals_received.max()])

            goals_received
teams
Vilafranca             172